server:
  port: 8010

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis所在路径
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml #mapper映射文件


spring:
  application:
    name: service
  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/house_keep?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

api-url: /page